name: Build Latest

on: 
  push:
  workflow_dispatch:
  schedule:
    - cron: 30 1 * * *

env:
  DOTNET_SDK_VERSION: '8.0.*'

jobs:

  build-win-x64-arm64:
    
    runs-on: windows-latest
    
    steps:
      
      - uses: actions/checkout@v1

      - name: Set up dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}

      - name: Upload Artifact[win-x64]
        uses: actions/upload-artifact@v3.1.3
        with:
          name: BBDown_win-x64
          path: artifact-x64\BBDown.exe

      - name: Upload Artifact[win-arm64]
        uses: actions/upload-artifact@v3.1.3
        with:
          name: BBDown_win-arm64
          path: artifact-arm64\BBDown.exe
  

  build-linux-x64:
    
    runs-on: ubuntu-latest
    container: ubuntu:18.04
    
    steps:
      
      - run: apt-get update
      - run: apt-get install -y curl wget
      - uses: actions/checkout@v1
      - name: Set up dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
      - run: apt-get install -y libicu-dev libcurl4-openssl-dev zlib1g-dev libkrb5-dev
      - run: dotnet publish BBDown -r linux-x64 -c Release -o artifact
      
      - name: Upload Artifact[linux-x64]
        uses: actions/upload-artifact@v3.1.3
        with:
          name: BBDown_linux-x64
          path: artifact/BBDown

  build-linux-arm64:
    
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-cross-arm64-20220312201346-b2c2436
    
    steps:
      
      - uses: actions/checkout@v1
      - name: Set up dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
      
      - name: Upload Artifact[linux-arm64]
        uses: actions/upload-artifact@v3.1.3
        with:
          name: BBDown_linux-arm64
          path: artifact/BBDown
          
  build-mac-x64-arm64:
    
    runs-on: macOS-latest
    
    steps:
      
      - uses: actions/checkout@v1
      
      - name: Set up dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}

      
      - name: Upload Artifact[osx-x64]
        uses: actions/upload-artifact@v3.1.3
        with:
          name: BBDown_osx-x64
          path: artifact-x64/BBDown
          
      - name: Upload Artifact[osx-arm64]
        uses: actions/upload-artifact@v3.1.3
        with:
          name: BBDown_osx-arm64
          path: artifact-arm64/BBDown
